version: '3'
services:
   app:
    container_name: image_store
    build: .
    ports: 
      - 8081:8081 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - imagestore-mysql          
    networks:
      - imagestore


   imagestore-mysql:
     image: mysql:5.7
     container_name: db_mysql
     restart: always
     ports: 
       - "3306:3306"
     environment: 
       - MYSQL_ROOT_HOST=% 
       - MYSQL_USER=${DB_USER}
       - MYSQL_PASSWORD=${DB_PASSWORD}
       - MYSQL_DATABASE=${DB_NAME}
       - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
     expose:
       # Opens port 3306 on the container
       - '3306'
     volumes:
       - imagestore-mysql:/var/lib/mysql
       - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
     networks:
       - imagestore
 
volumes:
  api:
  imagestore-mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  imagestore:
    driver: bridge